global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using OrderSphere.BuildingBlocks.Blob;
global using OrderSphere.BuildingBlocks.Infrastructure.Blob;
global using OrderSphere.BuildingBlocks.Security;
global using OrderSphere.BuildingBlocks.StronglyTypedIds;
global using OrderSphere.Invoicing.Application.Abstractions;
global using OrderSphere.Invoicing.Domain.Entities;
