

POST https://localhost:61302/CheckoutCart
Content-Type: application/json

{
  "customerId": "94f8c010-5bc9-4b80-9e77-ff5359766676",
  "shippingAddress": {
    "firstName": "Moritz",
    "lastName": "Waldau",
    "street": "Wasserwerkstr. 12",
    "city": "Wedemark",
    "postalCode": "30900",
    "country": "Germany"
  },
  "paymentMethod": 1
}

