using OrderSphere.Advisory.Api.Configuration;

namespace OrderSphere.Advisory.Api.Voice;

public static class VoiceEndpoints
{
    public static RouteGroupBuilder MapAdvisorVoiceEndpoints(this RouteGroupBuilder group)
    {
        // POST /advisor/voice/transcribe
        // Body: raw WAV bytes (16 kHz / 16-bit / mono, generated by the browser JS interop).
        // Returns: { "text": "..." }
        // Returns 501 when Speech:Region is not configured.
        group.MapPost("/voice/transcribe", async (
            HttpRequest request,
            SpeechService speech,
            CancellationToken ct) =>
        {
            if (!speech.IsEnabled)
                return Results.StatusCode(StatusCodes.Status501NotImplemented);

            using var ms = new MemoryStream();
            await request.Body.CopyToAsync(ms, ct);
            var wavBytes = ms.ToArray();

            if (wavBytes.Length <= 44)
                return Results.BadRequest("Audio payload too small or missing WAV header.");

            var text = await speech.TranscribeAsync(wavBytes, ct);
            return Results.Ok(new { text });
        })
        .RequireRateLimiting(RateLimitingExtensions.ChatPolicy);

        // POST /advisor/voice/synthesize
        // Body: { "text": "..." }
        // Returns: audio/mpeg (MP3)
        // Returns 501 when Speech:Region is not configured.
        group.MapPost("/voice/synthesize", async (
            SynthesizeRequest req,
            SpeechService speech,
            CancellationToken ct) =>
        {
            if (!speech.IsEnabled)
                return Results.StatusCode(StatusCodes.Status501NotImplemented);

            if (string.IsNullOrWhiteSpace(req.Text))
                return Results.BadRequest("Text must not be empty.");

            var audio = await speech.SynthesizeAsync(req.Text, ct);
            if (audio.Length == 0)
                return Results.Problem("Speech synthesis failed.", statusCode: StatusCodes.Status502BadGateway);

            return Results.Bytes(audio, "audio/mpeg");
        })
        .RequireRateLimiting(RateLimitingExtensions.ChatPolicy);

        return group;
    }
}

public sealed record SynthesizeRequest(string Text);
