global using FluentAssertions;
global using MockQueryable.NSubstitute;
global using NSubstitute;
global using OrderSphere.BuildingBlocks.StronglyTypedIds;
global using OrderSphere.Webhooks.Application.Abstractions;
global using OrderSphere.Webhooks.Domain.Entities;
global using OrderSphere.Webhooks.Domain.Enums;
global using OrderSphere.Webhooks.Domain.Errors;
global using Xunit;
