api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--azure-service-bus
        value: '{{ .Env.AZURE_SERVICE_BUS_SERVICEBUSENDPOINT }}'
      - name: connectionstrings--ordering-db
        value: '{{ .Env.POSTGRES_CONNECTIONSTRING }};Database=ordering-db'
      - name: keycloak--clientsecret
        value: '{{ securedParameter "ordering_worker_secret" }}'
  template:
    containers:
      - image: {{ .Image }}
        name: ordersphere-ordering-worker
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: AZURE_SERVICE_BUS_HOST
            value: '{{ .Env.AZURE_SERVICE_BUS_SERVICEBUSHOSTNAME }}'
          - name: AZURE_SERVICE_BUS_URI
            value: '{{ .Env.AZURE_SERVICE_BUS_SERVICEBUSENDPOINT }}'
          - name: Keycloak__Authority
            value: '{{ parameter "keycloak_realm_authority" }}'
          - name: Keycloak__ClientId
            value: ordering-worker
          - name: ORDERING_DB_DATABASENAME
            value: ordering-db
          - name: ORDERING_DB_HOST
            value: '{{ .Env.POSTGRES_HOSTNAME }}'
          - name: ORDERING_DB_JDBCCONNECTIONSTRING
            value: jdbc:postgresql://{{ .Env.POSTGRES_HOSTNAME }}/ordering-db?sslmode=require&authenticationPluginClassName=com.azure.identity.extensions.jdbc.postgresql.AzurePostgresqlAuthenticationPlugin
          - name: ORDERING_DB_PORT
            value: "5432"
          - name: ORDERING_DB_URI
            value: postgresql://{{ .Env.POSTGRES_HOSTNAME }}/ordering-db
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: ConnectionStrings__azure-service-bus
            secretRef: connectionstrings--azure-service-bus
          - name: ConnectionStrings__ordering-db
            secretRef: connectionstrings--ordering-db
          - name: Keycloak__ClientSecret
            secretRef: keycloak--clientsecret
    scale:
      minReplicas: 1
tags:
  azd-service-name: ordersphere-ordering-worker
  aspire-resource-name: ordersphere-ordering-worker
